### ISSUE TITLE
https://tensorflow.rstudio.com/install/

### ISSUE THREAD

**Issue by chaosssss123** [t-kalinowski/tensorflow.rstudio.com#67] opened 2023-10-17 09:18 UTC
this does not work. r studio crashes-fatal error every time I run install_tensorflow(). I have tried everything. ARe you going to advise us on how to successfully deal with ti or will you remain silent?

**Comment by t-kalinowski** [comment] 2023-10-17 13:29
Duplicate of https://github.com/rstudio/tensorflow/issues/585

**Closed as completed by t-kalinowski** 2023-10-17 13:29 UTC
